## Import Necessary Libraries

In [1]:
import numpy as np
import pandas as pd

## Extraction Layer

In [4]:
globex_df = pd.read_csv(r"C:\Users\Faith Audu\Desktop\10Alytics\10 ALYTICS GIT FILE\Globex_Retail_Project\dataset\rawdata\globex_retail_data - globex_retail_data.csv")

In [5]:
globex_df.head()

,Customer_ID,Order_ID,Order_Date,Product_Category,Product_Sub_Category,Quantity,Price,Discount,Customer_Location,Revenue
0,CUST_013738,ORD_00102406,2023-01-01,Home & Garden,Gardening Tools,1,419.19,0.00,TN,419.1900
1,CUST_011726,ORD_00102902,2023-01-01,Electronics,Laptops,1,222.37,0.09,TN,202.3567
2,CUST_010891,ORD_00103864,2023-01-01,Electronics,Laptops,6,1107.65,0.00,IN,6645.9000
3,CUST_011452,ORD_00103560,2023-01-01,Electronics,Gaming Consoles,5,288.84,0.00,MA,1444.2000
4,CUST_010886,ORD_00100632,2023-01-02,Electronics,Headphones,1,191.27,0.00,AZ,191.2700

In [6]:
globex_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           5000 non-null   object
 1   Order_ID              5000 non-null   object
 2   Order_Date            5000 non-null   object
 3   Product_Category      5000 non-null   object
 4   Product_Sub_Category  5000 non-null   object
 5   Quantity              5000 non-null   int64
 6   Price                 5000 non-null   float64
 7   Discount              5000 non-null   float64
 8   Customer_Location     5000 non-null   object
 9   Revenue               5000 non-null   float64
dtypes: float64(3), int64(1), object(6)
memory usage: 390.8+ KB

In [7]:
globex_df.columns

Index(['Customer_ID', 'Order_ID', 'Order_Date', 'Product_Category',
       'Product_Sub_Category', 'Quantity', 'Price', 'Discount',
       'Customer_Location', 'Revenue'],
      dtype='object')

## Data Cleaning and Transformation

In [8]:
#drop missing values
globex_df.dropna(subset=['Customer_ID', 'Order_ID'], inplace=True)

In [9]:
globex_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           5000 non-null   object
 1   Order_ID              5000 non-null   object
 2   Order_Date            5000 non-null   object
 3   Product_Category      5000 non-null   object
 4   Product_Sub_Category  5000 non-null   object
 5   Quantity              5000 non-null   int64
 6   Price                 5000 non-null   float64
 7   Discount              5000 non-null   float64
 8   Customer_Location     5000 non-null   object
 9   Revenue               5000 non-null   float64
dtypes: float64(3), int64(1), object(6)
memory usage: 390.8+ KB

In [10]:
# Convert Order_date from string to datetime object
globex_df['Order_Date'] = pd.to_datetime(globex_df ['Order_Date'])

In [11]:
globex_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           5000 non-null   object
 1   Order_ID              5000 non-null   object
 2   Order_Date            5000 non-null   datetime64[ns]
 3   Product_Category      5000 non-null   object
 4   Product_Sub_Category  5000 non-null   object
 5   Quantity              5000 non-null   int64
 6   Price                 5000 non-null   float64
 7   Discount              5000 non-null   float64
 8   Customer_Location     5000 non-null   object
 9   Revenue               5000 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 390.8+ KB

In [ ]:
# customer_df = globex_df[['Customer_ID', 'Customer_Location']].copy_duplicates().reset_index(drop=True)
# Customer_df.head()

In [12]:
globex_df.columns

Index(['Customer_ID', 'Order_ID', 'Order_Date', 'Product_Category',
       'Product_Sub_Category', 'Quantity', 'Price', 'Discount',
       'Customer_Location', 'Revenue'],
      dtype='object')

In [15]:
customers_df = globex_df[['Customer_ID', 'Customer_Location']].copy().drop_duplicates().reset_index(drop=True)
customers_df.head()

   Customer_ID Customer_Location
0  CUST_013738                TN
1  CUST_011726                TN
2  CUST_010891                IN
3  CUST_011452                MA
4  CUST_010886                AZ

In [23]:
Orders_df = globex_df[['Order_Date', 'Order_ID']].copy().drop_duplicates().reset_index(drop=True)
Orders_df.head()

  Order_Date      Order_ID
0 2023-01-01  ORD_00102406
1 2023-01-01  ORD_00102902
2 2023-01-01  ORD_00103864
3 2023-01-01  ORD_00103560
4 2023-01-02  ORD_00100632

In [20]:
globex_df.columns

Index(['Customer_ID', 'Order_ID', 'Order_Date', 'Product_Category',
       'Product_Sub_Category', 'Quantity', 'Price', 'Discount',
       'Customer_Location', 'Revenue'],
      dtype='object')

In [21]:
products_df = globex_df[['Product_Category', 'Product_Sub_Category']].copy().drop_duplicates().reset_index(drop=True)
products_df.head()

  Product_Category Product_Sub_Category
0    Home & Garden      Gardening Tools
1      Electronics              Laptops
2      Electronics      Gaming Consoles
3      Electronics           Headphones
4         Clothing                Shoes

In [27]:
price_df = globex_df[['Price', 'Discount', 'Revenue']].copy().drop_duplicates().reset_index(drop=True)
price_df.head()

     Price  Discount    Revenue
0   419.19      0.00   419.1900
1   222.37      0.09   202.3567
2  1107.65      0.00  6645.9000
3   288.84      0.00  1444.2000
4   191.27      0.00   191.2700

In [28]:
Quantity_df = globex_df[['Quantity']].copy().drop_duplicates().reset_index(drop=True)
Quantity_df.head()

   Quantity
0         1
1         6
2         5
3         4
4         2

In [37]:
customers_df.to_csv(r'dataset/cleaneddata/customers.csv', index=false)
orders_df.to_csv(r'dataset/cleaneddata/orders.csv', index=false)
products_df.to_csv(r'dataset/cleaneddata/products.csv', index=false)
price_df.to_csv(r'dataset/cleaneddata/price.csv', index=false)
Quantity_df.to_csv(r'dataset/cleaneddata/Quantity.csv', index=false)

NameError: name 'false' is not defined

# Save the tables to csvs

In [36]:
customers_df.to_csv(r'dataset/cleaneddata/customers.csv')
Orders_df.to_csv(r'dataset/cleaneddata/orders.csv')
products_df.to_csv(r'dataset/cleaneddata/products.csv')
price_df.to_csv(r'dataset/cleaneddata/price.csv')
Quantity_df.to_csv(r'dataset/cleaneddata/Quantity.csv')